### ISSUE TITLE
Info from the Upstream

### ISSUE THREAD

**Issue by svettwer** [postfinance/citrus-simulator#22]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: 
Hi Guys,

awesome news from our side. Due to your fork, I escalated the situation and was successful. 

The management decided to open up the project **now** to a selected set of external developers so that we are able to maintain the project again. So I'd like to suggest the following:
- I'll open the project to external developers
- You propose a PR with your changes from your fork
- We'll review the changes and release a new simulator version with your changes, Spring Boot 2, etc. during next week.

What do you think? IMHO this is a big step forward and I'm absolutely happy of that progress! Thank you so much for helping me to make progress on that!

In addition, it seems that you are very interested in the progress of the project. Let us talk about your role in the project in the future and how you see yourself in it.

BR
Sven

:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by svettwer** [comment]
CC @christophd :wink:

**Comment by bbortt** [comment]
WOW - that's great news. and exactly what we wanted to achieve: an actively maintained `citrus-simulator` with an enthusiastic community. We'll first of all propose a merge to the upstream repository. Then maybe open Issues with our ideas one by one in order to discuss them further.
